[build.environment]
  NODE_VERSION = "16"

[build]
  command = "pnpm run build"
  publish = "netlify"
  functions = "netlify/functions"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
